name: translation-lint

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: 'Translation Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: '.tool-versions'
      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/honojs/website.git
          git fetch upstream main
      - name: Get merge base
        run: echo "MERGE_BASE=$(git merge-base upstream/main HEAD)" >> $GITHUB_ENV
      - name: Run translation lint
        run: node ./scripts/translation-lint.ts --line-count ${{ env.MERGE_BASE }} HEAD
